
namespace BankingWinAppForms
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            label4 = new Label();
            label5 = new Label();
            label6 = new Label();
            label7 = new Label();
            txtName = new TextBox();
            txtAdd = new TextBox();
            txtBalance = new TextBox();
            txtAcc = new TextBox();
            dtDate = new DateTimePicker();
            btnDeposit = new Button();
            btnWithdraw = new Button();
            btnShow = new Button();
            btnClear = new Button();
            SuspendLayout();
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Location = new Point(131, 32);
            label1.Name = "label1";
            label1.Size = new Size(24, 20);
            label1.TabIndex = 0;
            label1.Text = "ID";
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Location = new Point(131, 109);
            label2.Name = "label2";
            label2.Size = new Size(49, 20);
            label2.TabIndex = 1;
            label2.Text = "Name";
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Location = new Point(131, 182);
            label3.Name = "label3";
            label3.Size = new Size(62, 20);
            label3.TabIndex = 2;
            label3.Text = "Address";
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Location = new Point(131, 268);
            label4.Name = "label4";
            label4.Size = new Size(61, 20);
            label4.TabIndex = 3;
            label4.Text = "Balance";
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Location = new Point(131, 364);
            label5.Name = "label5";
            label5.Size = new Size(41, 20);
            label5.TabIndex = 4;
            label5.Text = "Date";
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Location = new Point(131, 459);
            label6.Name = "label6";
            label6.Size = new Size(121, 20);
            label6.TabIndex = 5;
            label6.Text = "Account Number";
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Location = new Point(379, 32);
            label7.Name = "label7";
            label7.Size = new Size(185, 20);
            label7.TabIndex = 6;
            label7.Text = "Auto Generated By System";
            // 
            // txtName
            // 
            txtName.Location = new Point(368, 109);
            txtName.Name = "txtName";
            txtName.Size = new Size(250, 27);
            txtName.TabIndex = 7;
            // 
            // txtAdd
            // 
            txtAdd.Location = new Point(368, 182);
            txtAdd.Name = "txtAdd";
            txtAdd.Size = new Size(250, 27);
            txtAdd.TabIndex = 8;
            // 
            // txtBalance
            // 
            txtBalance.Location = new Point(368, 268);
            txtBalance.Name = "txtBalance";
            txtBalance.Size = new Size(250, 27);
            txtBalance.TabIndex = 9;
            // 
            // txtAcc
            // 
            txtAcc.Location = new Point(368, 456);
            txtAcc.Name = "txtAcc";
            txtAcc.Size = new Size(250, 27);
            txtAcc.TabIndex = 10;
            txtAcc.Text = "Auto Generated By System";
            // 
            // dtDate
            // 
            dtDate.Location = new Point(368, 357);
            dtDate.Name = "dtDate";
            dtDate.Size = new Size(250, 27);
            dtDate.TabIndex = 11;
            // 
            // btnDeposit
            // 
            btnDeposit.Location = new Point(131, 545);
            btnDeposit.Name = "btnDeposit";
            btnDeposit.Size = new Size(94, 29);
            btnDeposit.TabIndex = 12;
            btnDeposit.Text = "Deposit";
            btnDeposit.UseVisualStyleBackColor = true;
            btnDeposit.Click += btnDeposit_Click;
            // 
            // btnWithdraw
            // 
            btnWithdraw.Location = new Point(311, 545);
            btnWithdraw.Name = "btnWithdraw";
            btnWithdraw.Size = new Size(94, 29);
            btnWithdraw.TabIndex = 13;
            btnWithdraw.Text = "Withdraw";
            btnWithdraw.UseVisualStyleBackColor = true;
            btnWithdraw.Click += btnWithdraw_Click;
            // 
            // btnShow
            // 
            btnShow.Location = new Point(498, 545);
            btnShow.Name = "btnShow";
            btnShow.Size = new Size(94, 29);
            btnShow.TabIndex = 14;
            btnShow.Text = "Show";
            btnShow.UseVisualStyleBackColor = true;
            btnShow.Click += btnShow_Click;
            // 
            // btnClear
            // 
            btnClear.Location = new Point(738, 545);
            btnClear.Name = "btnClear";
            btnClear.Size = new Size(94, 29);
            btnClear.TabIndex = 15;
            btnClear.Text = "Clear";
            btnClear.UseVisualStyleBackColor = true;
            btnClear.Click += btnClear_Click;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = SystemColors.GradientInactiveCaption;
            ClientSize = new Size(914, 601);
            Controls.Add(btnClear);
            Controls.Add(btnShow);
            Controls.Add(btnWithdraw);
            Controls.Add(btnDeposit);
            Controls.Add(dtDate);
            Controls.Add(txtAcc);
            Controls.Add(txtBalance);
            Controls.Add(txtAdd);
            Controls.Add(txtName);
            Controls.Add(label7);
            Controls.Add(label6);
            Controls.Add(label5);
            Controls.Add(label4);
            Controls.Add(label3);
            Controls.Add(label2);
            Controls.Add(label1);
            Name = "Form1";
            Text = "Login_Form";
            Load += Form1_Load;
            ResumeLayout(false);
            PerformLayout();
        }

        private void btnDeposit_Click(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }

        #endregion

        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private TextBox txtName;
        private TextBox txtAdd;
        private TextBox txtBalance;
        private TextBox txtAcc;
        private DateTimePicker dtDate;
        private Button btnDeposit;
        private Button btnWithdraw;
        private Button btnShow;
        private Button btnClear;
    }
}
